version: "3.8"
services:

  proxy:
    build:
      context: ./proxy
    depends_on:
    - container_a
    - container_b
    - container_c
    - container_d
    ports:
    - 10000:10000
    - 9901:9901
    - 80:80

  container_a:
    build:
      context: ./echo
    hostname: container_a

  container_b:
    build:
      context: ./echo
    hostname: container_b

  container_c:
    build:
      context: ./echo
    hostname: container_c

  container_d:
    build:
      context: ./echo
    hostname: container_d
