resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: example_proxy_cluster
  type: STATIC
  connect_timeout: 5s
  load_assignment:
    cluster_name: example_proxy_cluster
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 172.21.0.4
              port_value: 8080
      - endpoint:
          address:
            socket_address:
              address: 172.21.0.5
              port_value: 8080
  health_checks:
  - timeout: 2s
    interval: 1s
    interval_jitter: 1s
    unhealthy_threshold: 3
    healthy_threshold: 3
    tcp_health_check: {}
